version: "3"

services:
  certbot:
    restart: always
    container_name: certbot
    image: 5pecia1/certbot-namecheap:latest
    # build: ./
    env_file:
      - .env-namecheap
      - .env-nginx
    environment:
      - DRY_RUN=true # INFO: FOR TEST
    entrypoint: "/home/certonly.sh && /home/renew.sh" # WRAN: DRY_RUN=true can't start renew
    # entrypoint: "/home/renew.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certonly.sh:/home/certonly.sh
      - ./renew.sh:/home/renew.sh
      - ./letsencrypt-namecheap-dns-auth.sh:/home/letsencrypt-namecheap-dns-auth.sh
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/log:/var/log
    labels:
      5hare: "certbot"
